### PR TITLE
Create unit test code coverage tasks on libraries

### PR DESCRIPTION
**Pull request by cswagner**
Prerequisite for [c-8732](https://youtrack.mobiledefense.com/issue/c-8732) and [c-8731](https://youtrack.mobiledefense.com/issue/c-8731).

### CODE REVIEW

**Comment by cswagner** [comment]
@lithid is there a good way to test these plugins locally i.e. without publishing to bintray?

**Comment by lithid** [comment]
> @lithid is there a good way to test these plugins locally i.e. without publishing to bintray?

Yeah, I was testing using this method.

We need to update `build.gradle` for this project to `'com.android.tools.build:gradle:2.1.0'`.

I went into the root project and cloned the plugin into a folder called `buildSrc`.

```
git clone git@github.com:mobiledefense/gradle_coverage_report.git buildSrc
```

I then comment out the follow lines in the root `build.gradle` so it doesn't attempt to pull from maven/jcenter.

```
maven { url 'https://dl.bintray.com/mobiledefenseopensource/maven' }
classpath 'com.mobiledefense.gradle:gradle_coverage_report:0.0.1'
```

I go into the `buildSrc` dir and run `./gradlew install`

Then the coverage reports should work with the local source. There are better ways using `buildSrc` with multiple projects, but I haven't configured anything like that yet, but can be done in the future if we need to test multiple plugins locally.

**Comment by cswagner** [comment]
I followed [this stackoverflow post](http://stackoverflow.com/a/16468836) to test the plugin in the common repo.

**Comment by cswagner** [comment]
@lithid this is ready for review.

**Comment by cswagner** [comment]
@lithid yeah, I think that's fine.

**Comment by lithid** [comment]
@cswagner I added a simple commit to inline the gradle version for this project with the latest version we use everywhere else. We can always drop it if we need to add this in another PR.

**Comment by lithid** [comment]
I verified this on the SDK/Common repo

**Comment by lithid** [comment]
:+1: Ready for merge.

**Note:** Please interactively rebase this branch onto latest master and squash any fixups before merging this pull request. Even if you don't have any fixups, make sure to rebase.

~~~shell
$ git checkout master
$ git pull origin master

$ git checkout <this-branch-name>
$ git rebase -i master --autosquash
~~~

**Comment by cswagner** [comment]
>I added a simple commit to inline the gradle version for this project with the latest version we use everywhere else. We can always drop it if we need to add this in another PR.

Sounds good to me. Thanks for the review!

**Pull request merged**
